# Generated by Django 5.0.4 on 2024-04-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='math_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('teacher_name', models.CharField(blank=True, max_length=255)),
                ('class_name', models.CharField(blank=True, max_length=255)),
                ('assignment_date', models.DateField(blank=True, null=True)),
                ('assignment_title', models.CharField(max_length=500)),
            ],
        ),
    ]
