# Generated by Django 5.0.4 on 2024-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mathwork", "0003_imagemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("canvas_data", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="ImageModel",
        ),
    ]
