# Generated by Django 5.0.4 on 2024-05-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathwork', '0004_drawing_delete_imagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mathassignment',
            old_name='problems',
            new_name='math_input',
        ),
        migrations.AddField(
            model_name='mathassignment',
            name='canvas_data',
            field=models.TextField(blank=True),
        ),
    ]
